language: node_js
node_js: node
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE noteful_test;' -U postgres
- psql -U postgres -f ./db/noteful.2.sql noteful_test
deploy:
  provider: heroku
  api_key:
    secure: gue2FxfaWdExeXZjyn/nzMMWn40WGWl2eHRxfCIJ1nk3bdohNBluRoI05rV59RYeY5CL/b6hzGiVr1AL8DeuZ8y/g0cjlo64ZpL+k972/tZ+xSceZ5Fx9E15Fiq7JF9fPWk2APbKu63ZqmMgy0C7AICZPjNJqPiX675LWRL2neTsuT5kt4kV5SSv2Qv7269jglctraLA93gLuIIDP4ukfD97vyLVimBzsGNiCUxWBWEERuFOQUSU/MYtX7RWOk0Wboc+2+o+YXHV4cO1iw7ZsCJfxnNT5crpfhpDPcmzMnTXu2XX5+9eq4EVkSBMrc7NrCsNmmc1LeZf7N1lw6Itlm4YmUjZD0VwhmB8HPyTXsIjDW50PZH5rDly6/z1IUAH04ot3aChhQPmjr8ly8Fx9PdtegEok0IRp8dep0GzsoAXyQRZx0bLer8KMlkEVPcKtzD7aMwCEutkf8t0cRqo/YUDyepxS6OEGLrNkHWacuBYgmxD1ef64nG35UE3qv4/+mlEi9FSj93sqjNT2qBP2EIEViUWeDzvaMJXNLVcgwCym0shPQ+yhn+vu3aoMf8ivFgXEny47x+Lw8peBjH0y6S1VYuOXShLwCeG4aWVvjyo8d516NLZCnxidO4+Rw+RDnJRsZvfTfOnqESz1FUl0xFG/hCmL6LJX/OcYue12bI=
  app: nameless-peak-50575
  on:
    repo: thinkful-ei18/Ali-Noteful-App-V2
