language: node_js
node_js: node
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE noteful_test;' -U postgres
- psql -U postgres -f ./db/noteful.2.sql noteful_test
deploy:
  provider: heroku
  api_key:
    secure: XsFuLTkK4Lfyk6761Lemdv0ClWDo67PCvkyb1sJX+u/ISDfu5u5Jy91NUVt1aIgAYWI4ASbJ7QBpAznATn9S5iy74PYC1YmMlElQ8x+fZcWYBHUyu89lWM0yn3QQqkEYoOpYszApC//pC3+UjuIEj7TenGhXddmd6uHSavcbZon1j4coNRddER7ughLJypst7yMDlFkM2RQlYkjTtfNL/0vlfM8PUpldPKjOBL2Al1h8ssYh55k5L8RtFTCpxLmaBy/u6m2i8PPqkHVKf4t6wb64aL5woLW1AupJ0aoCqVdGF0dw1c4xhPYiJ1xb2JSuCuPlJyJ+TmLLaJFDSMZdwMyejWraHwi26UA67HbBBLw2mrM8r6O0YFAnQm6WzfxbDQo0ceD2C/EESYWSmffNoYUyCs+c0YBvlJmmhdqTxWz2Y+rP4ixUPnxHR2ATUUjfbvvkdzrfC5ZwPZNyHLm64WOocYBNgtkHRJcqC+DFWzW303FpWwbezlJ99g8z1VaeWm9Xe0YXZYqdn62nXVC4ypv4BGQTpgLe8fDZx0ag1yYKeAbzk4cQdtmRdIQdR6T9cvoVHnSdpfNUw+7cOsiIZIH9EAX8RtsNO9g7M1c/KZByn2Lw8BbU7TTEotVA/YHYTM7/3VyTiUYMTaxweV2a7Mj3SJPF0JCQxJ10QWex7Gs=
  app: nameless-peak-50575
  on:
    repo: thinkful-ei18/Ali-Noteful-App-V2
